taxiride(
	driver(
		carnumber(37),
		fullname(
			firstname('Peter'),
			middlename('C.'),
			lastname('Jones'))),
	passengers,
	transportinformation(
		date('9/27'),
		destination(
			street(
				streetnumber(12),
				streetname('Main
					St')),
			municipality(
				municipalityname('Fredericton'),
				provincename('NB'))),
		fare(12.50))).
